### ISSUE TITLE
Release auf Maven Central

### ISSUE THREAD

**Issue by thomasrichner-oviva** [gematik/lib-ihe-xds#7]
Hi there!

We've been using this library for ePA 2.6 in production and are now upgrading to ePA 3.0.
As far as I can tell the latest release is not yet on Maven Central: https://central.sonatype.com/artifact/de.gematik.epa/lib-ihe-xds

Are there any plans to release it there? If yes, when?

Thanks! We would highly appreciate a maven release :)
Thomas

**Comment by sonerd** [comment]
Hi @thomasrichner-oviva ,

we have published the latest release (2.0.2) of the lib at maven central.

Regards
Soner

**Comment by thomasrichner-oviva** [comment]
Thanks, works like a charm!
